[MIG][17.0] project_todo: migrate to 17.0
Viindoo/OpenUpgrade pull request #643
Opened 2024-05-25 01:40 UTC by haumenphai

task: https://viindoo.com/web?debug=1#id=91060&cids=1&menu_id=289&action=409&active_id=475&model=project.task&view_type=form

2024-06-04 02:23 UTC, royle-viindoo commented on openupgrade_scripts/scripts/project_todo/17.0.1.0/pre-migration.py
> +def _migrate_attached_records(env):
@haumenphai em thay hàm này bằng openupgrade.merge_models() nhé, trong đó nó chịu trách nhiệm xử lý rất nhiều dữ liệu

2024-06-04 04:24 UTC, haumenphai commented on openupgrade_scripts/scripts/project_todo/17.0.1.0/pre-migration.py
> +def _migrate_attached_records(env):
vâng a

2024-06-05 09:21 UTC, royle-viindoo commented
@duong77476-viindoo em review và approve nhé

2024-06-05 10:05 UTC, duong77476-viindoo requested changes
Ngoài ra, trong file docsource ở line module `note` thì e thêm `Done` vào để thể hiện là có làm gì đó, a check mấy phiên bản trước cũng hay làm thế

2024-06-05 10:05 UTC, duong77476-viindoo commented on openupgrade_scripts/scripts/project_todo/17.0.1.0/pre-migration.py
> +        ALTER TABLE project_task ADD COLUMN note_id INTEGER;
```suggestion
        ALTER TABLE project_task ADD COLUMN openupgrade_legacy_note_id INTEGER;
```
Có thể nên đổi tên cột tạm này thành cái tên j khác, ai đó có thể phát triển tính năng mà từ note ra task ở v16, và trên `project.task` họ có trường này `note_id`

2024-06-06 02:12 UTC, duong77476-viindoo approved these changes
lỗi pre-commit
Ngoài ra thì LGTM

2024-06-06 02:12 UTC, duong77476-viindoo requested changes

2024-06-06 02:12 UTC, duong77476-viindoo commented on openupgrade_scripts/scripts/project_todo/17.0.1.0/pre-migration.py
> +    openupgrade.merge_models(env.cr, "note.note", "project.task", "openupgrade_legacy_note_id")
```suggestion
    openupgrade.merge_models(
        env.cr, "note.note", "project.task", "openupgrade_legacy_note_id"
    )
```

2024-06-07 03:30 UTC, merged